services:
  - type: web
    name: blog-web-app
    runtime: python
    runtimeVersion: 3.12
    buildCommand: ./build.sh
    startCommand: gunicorn blog_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,*.render.com
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString

databases:
  - name: blog-db
    databaseName: blog_db
    user: blog_user
